### ISSUE TITLE
title get to "null" if you press off button first

### ISSUE THREAD

**Issue by HoerMirAuf** [curtiscde/flashing-page-title-notification#18]
I take your script to make a tab-notification.
Thank you very much for your work!!

But ... by pressing your off button first, your title will run into a "null" title,
This will appear if you take a onfocus element to switch off the tab-notification and get focus of the webside before a notification event is happen.

Workaorund is with a onload  function to activate and deactivate the notification function.

**Comment by curtiscde** [comment]
Hi @HoerMirAuf thanks for raising this issue.

I was able to reproduce the bug and have created a fix for it (#20) which has been published as part of [v2.4.1](https://github.com/curtiscde/flashing-page-title-notification/releases/tag/v2.4.1).

You can demo this in use here:

https://flashing-page-title-notification.netlify.app/

Please let me know if you continue to have issues.
