### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by clibequilibrium** [curtiscde/flashing-page-title-notification#24]
Hi, thanks a lot for the package, it is very useful for my project. Do you provide licensing terms, MIT or UNLICENSE ?

**Comment by curtiscde** [comment]
Hi @clibequilibrium, I'm glad you have found the package of use!

I have added an MIT license to the repo now:

https://github.com/curtiscde/flashing-page-title-notification?tab=MIT-1-ov-file
https://github.com/curtiscde/flashing-page-title-notification/blob/main/LICENSE

**Comment by clibequilibrium** [comment]
> Hi @clibequilibrium, I'm glad you have found the package of use!
> 
> 
> 
> I have added an MIT license to the repo now:
> 
> 
> 
> https://github.com/curtiscde/flashing-page-title-notification?tab=MIT-1-ov-file
> 
> https://github.com/curtiscde/flashing-page-title-notification/blob/main/LICENSE
> 
> 

Thank you so much!
